# Generated by Django 4.1 on 2022-09-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datam', '0002_todo_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='task',
            field=models.TextField(max_length=300),
        ),
    ]
